plugins {
    id 'com.android.application'
}
android {
    namespace 'com.example.cleanxposed'
    compileSdk 33
    defaultConfig {
        applicationId "com.example.cleanxposed"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
